### ISSUE TITLE
Bert-Vits2 2.3无法使用

### ISSUE THREAD

**Issue by Zsural** [qiye45/micro-and-vits#2]
当我发现bertvits2文件夹下的bert模型都没法使用后，我尝试测试了运行exe，请问下面怎么解决下面的问题
D:\micro-and-vits\micro-and-vits5.4_bert_vits2\bertvits2>bertvits2.exe
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
cpu
【】
error
Traceback (most recent call last):
File "bertvits2jiami.py", line 169, in <module>
File "bertvits2jiami.py", line 153, in m
NameError: name 'exit' is not defined
【8148】 Failed to execute script 'bertvits2jiami' due to unhandled exception!

**Comment by qiye45** [comment]
用整合包自带的

**Comment by Zsural** [comment]
就是从B站下载的整合包资源出问题啊，下面是B站下载链接：https://pan.quark.cn/s/0ddd9758ff73，我没有用第三方资源啊

**Comment by Zsural** [comment]
就是从B站下载的整合包资源出问题啊，我没有用第三方资源啊。下面是B站下载链接：https://pan.quark.cn/s/0ddd9758ff73

**Comment by Zsural** [comment]
为甚么这么设置加载模型不成功呢，明明是整合包自带的资源确用不了
![2024-08-09_214935](https://github.com/user-attachments/assets/1a050389-9afe-41ca-93a1-dea7de58a7b9)

**Comment by qiye45** [comment]
模型地址填这几个
![image](https://github.com/user-attachments/assets/d0919245-e2e1-4d0b-b056-a23251cd19a4)
